server:
  servlet:
    context-path: /myservice
management:
  endpoints:
    web:
      exposure:
        #include: health,info,env,beans
        include: "*"


kafka:
  topic: temp
spring:
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      keyDeserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      valueDeserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
  cloud:
    stream:
      bindings:
        input:
          destination: ${kafka.topic}

